*Modificada Abstractions para trabalhar com PostGreSql
NetDevPack/NetDevPack.Identity pull request #1
Opened 2020-06-06 14:39 UTC by eduprog

* Devido a necessidade de trabalhar com um banco de dados que não o SqlServer, fiz uma Modificação classe NetDevPack.Identity.Abstractions , onde foi criado um novo método de nome: AddNetDevPackContextIdentity que continua sendo uma extensão de IServiceColletion, mas que agora faz uso de um enum que define se será criado a migrations para SqlServer ou PostgreSql. 

*Método AddIdentityEntityFrameworkContextConfiguration ainda continua, para que não aconteça quebra de código em projetos já trabalhados.

@EduardoPires , primeiramente gostaria de lhe parabenizar pela iniciativa, ficou top demais, e de acordo com o que passa no curso asp net core enterprise, novamente parabenizar pelo curso, pois nele vi coisas que não imaginava em fazer em nosso sistema de gestão que estamos iniciando o projeto para que ele seja também web. Hoje temos um sistema de gestão para os mais variados seguimentos varejo, mas em winforms e bd postgreSql. O que você mostra em trabalhar com api's distribuídas, era o que já estava em meu esboço de projeto para fazer, só não sabia que eu poderia ter uma migration para cada api, sempre achei que teria problema quando uma outra api/dll tentasse alterar o banco. 

A parte de Mesangeria, sensacional, eu também não conhecia, somente tinha ouvido falar e me abriu vários horizontes e ideias para poder fazer uma aplicação mais coerente, mais resiliente, com recursos que eu não imaginava, pois pensar desktop, mesmo que remoto, é bem diferente do que pensar web. 

Enfim, peguei seu projeto e resolvi tentar colocar de uma maneira mais menos invasiva para poder usar em nosso banco de dados postgresql e de neste pull request. Espero que ajude, ou que você analise e veja se segui, boas práticas, usei o que deveria, se está pouco, se está muito. 

Agora deixa de falar de mim e vamos ao pull, não sei se optei pela melhor abordagem, pois a cada banco de dados que iremos usar, temos de adicionar o pacote dele no projeto, mas não vejo oura alternativa, a não ser que criasse derivações do NetDevPack.Indentity.SqlServer, NetDevPack.Indentity.Npgsql e assim por diante. 

Estou finalizando o curso enterprise, já termino o carrinho hoje e estou ansioso as aulas do próximo módulo. O que fiz no meu projeto foi que coloquei a parte de autenticação(identity) toda  em um bd pgsql que é o usamos no dia a dia, assim terei um servidor de identity em postgresql exclusivo para tal. 

Outras partes que irei criar em minha api, usarei outros dois bancos, um NoSql, provavelmente MongoDB para armazenar documentos apenas, e terei um outro Bd que será em postgresql onde ficaram os dados que não tem como fugir do relacional., 

PS: Como estou iniciando o trabalho com o git e github a pouquissimo tempom, confeso que é meu primeiro pull request, então não sei se deveria abrir uma issue e associar o pull a ela, se poderia fazer o fork, alterar e submeter, como fiz agora. Gostaria que fosse bem franco se fiz algo de errado para que possa melhorar para os próximos pull's. Até então sempre trabalhamos aqui com o AzureDevops, mas depois que github liberou os repositorios privados, vi com bons olhos, pois como nossa equipe é pequena, somos em 5, no Azure Devops é muita informação que acaba inflando para nós que somos poucos e fazemos vários projetos, errado, mas eu mesmo faço papel de PO e SM, coisa que não deveria. Mas eu mesmo como CEO da empresa , Idealizo os projetos, faço o rascunho para melhorias e lançava as Features, BackLog,Tasks , então sendo muita coisa para associar, documentos para subir e tal. No github pelo que estudei dele na semana passada, nos atende tranquilamente para controle do projeto, consegui configurar meu supervisor de suporte para poder abrir issues de Features, Bugs, enfim, ficou muito mais simples para nós. 

Agora chega já falei demais. Até a próxima, espero ter ajudado. Para mim aqui este projeto já está para ser anexado junto ao enterprise, simplificando e muito a parte de codificação, deixando o código limpinho. Parabéns novamente.

2020-06-06 14:46 UTC, eduprog commented
@EduardoPires esqueci de comentar, fiquei empolgado com meu primeiro pull, rsrs. 

Eu tive de tirar a referência do Icon no projeto para geração do Nuget porque quebrava a compilação. Ok.

2020-06-06 20:44 UTC, ralmsdeveloper requested changes

2020-06-06 20:44 UTC, ralmsdeveloper commented on src/NetDevPack.Identity/Abstractions.cs
> +                        return services.AddDbContext<NetDevPackAppDbContext>(options =>
IMHO:
Você deve mover para fora do `switch ` todas validações de argumentos, isso está causando DRY. a extensão fica mais consistente, dado o cenário que são argumentos obrigatórios.
Também acredito que isso está mais para uma Factory, fiquei pensando também se não poderia usar apenas `DbContextOptions` como argumento então, você deveria ser capaz de produzir algo assim:
```csharp
.AddDbContext<NetDevPackAppDbContext>(_ => new DbContextOptionsBuilder(options))
```

2020-06-06 20:49 UTC, ralmsdeveloper commented
Um outro detalhe importante é manter testes e exemplos separados basicamente para cada provider, no PR atual foi substituido a migração do SQL Server por PostgreSQL.
Algumas observações que podem ser consideradas:

- Ignorar arquivos de Migrações (.gitignore)
- Migrações separadas por providers
- Os testes de migrações devem ser capazes de produzir uma `migration ` em tempo de execução.

2020-06-06 20:49 UTC, ralmsdeveloper commented
/cc @EduardoPires

2020-06-06 23:54 UTC, EduardoPires commented
@eduprog Obrigado pela submissão, existem alguns pontos a serem melhorados no design e eu gostaria de uma abordagem com base na sugestão do @ralmsdeveloper onde uma factory pudesse ser passada como options ao invés de realizar o switch assim melhorando no conceito do OCP.

Essa PR não vou aprovar devido as melhorias de design, para os demais PRs é importante abrir uma issue, debatermos a abordagem e ai sim depois de acertado os detalhes aceitarei o PR. 

PS - Vamos utilizar o inglês para padronizar a comunicação para que todos entendam. 

Obrigado pela colaboração

2020-06-06 23:54 UTC, closed without merging

2020-06-09 03:12 UTC, EduardoPires commented
This need was solved in v1.1.1